/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  controller: string;
  decimals: number;
  description: string;
}
export type ExecuteMsg = {
  update_controller: {
    controller: string;
  };
} | {
  update_round_data: {
    answer: number;
  };
};
export type QueryMsg = {
  lastest_round_data: {};
} | {
  round_data: {
    round_id: number;
  };
} | {
  decimals: {};
} | {
  description: {};
} | {
  controller: {};
};
export type String = string;
export type Uint8 = number;
export type Uint128 = string;
export type Timestamp = Uint64;
export type Uint64 = string;
export interface RoundDataResponse {
  answer: Uint128;
  answered_in_round: number;
  round_id: number;
  updated_at: Timestamp;
}